import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald } from "next/font/google";
import "./globals.css";
import Link from "next/link"
import Image from "next/image"
import favicon2 from "../public/favicon2.svg"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "400"
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: "400"
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "YourFitJournal",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon2.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en" className="{`${geistSans.variable} ${geistMono.variable} ${oswald.variable} antialiased`}">
  <body className="text-white bg-black-100 font-geist-sans font-geist-mono font-oswald" >
    <nav className="flex items-center border-b border-b-emerald-200 bg-blue border-shadow-md">
      <div className= "flex justify-start items-center gap-0" >
        <Image
          className= "scale-25"
          src={favicon2}
          alt = "YourFitJournallogo"
        />
        <h1 className= "text-xl font-oswald">YourFitJournal</h1>
      </div>
      <div className= "flex gap-6 ">
          <Link href={"/"} className="flex justify-center items-center text-black h-10 w-20 bg-gray-50 rounded-2xl ml-200 hover:bg-gray-300"> Home </Link>
          <Link href={"/Login"} className="flex justify-center items-center text-black h-10 w-20 bg-gray-50 rounded-2xl"> Login </Link>
          <Link href={"/SignUp"}className="flex justify-center items-center text-black h-10 w-20 bg-gray-50 rounded-2xl"> Sign Up </Link>
      </div>
    </nav>
       {children}
      </body>
    </html>
  );
}
