import type { Metadata } from "next";
import { Geist, Oswald } from "next/font/google";
import "../../app/globals.css";
import { ClerkProvider, UserButton, SignInButton, SignUpButton, Show } from '@clerk/nextjs';
import {Navmain} from "../../components/ui/Navbar/MainNav"
import { Separator } from "../../components/ui/separator"
import {Footer} from "../../components/ui/footer"



const publishableKey = process.env.REACT_APP_CLERK_PUBLISHABLE_KEY; // Or the appropriate env var name


const geistSans = Geist({
  variable: '--font-geistSans',
  subsets: ["latin"],
  weight: "400"
});

const oswald = Oswald({
  variable: '--font-oswald',
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "YourFitJournal",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon2.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${oswald.variable} ${geistSans.variable}`}>
      <body className="text-white bg-linear-to-br from-black to-gray-800 {oswald.className}" ><ClerkProvider publishableKey={publishableKey}>
        <Navmain/>
          {children}
          <div className="mt-20">
          <Separator/>
          </div>
          <div className="mt-10">
          <Footer />
          </div>
        </ClerkProvider></body>
      
      
    </html>
  );
}
